gui:
  scrollHeight: 14 # about 1/2 page
  showIcons: true
  theme:
    selectedLineBgColor:
      - "#253333"
      - bold
    selectedRangeBgColor:
      - "#253333"
      - bold
    cherryPickedCommitFgColor:
      - "#253333"
      - bold
keybinding:
  commits:
    moveDownCommit: "<c-n>"
    moveUpCommit: "<c-p>"
