#!/usr/bin/env sh

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist on \
	window_topmost off \
	window_shadow off \
	window_animation_duration 0.0 \
	window_animation_frame_rate 120 \
	window_opacity off \
	insert_feedback_color 0xffd75f5f \
	active_window_border_color 0x60E49B5D \
	normal_window_border_color 0x00E49B5D \
	window_border_width 1 \
	window_border_radius 10 \
	window_border_blur off \
	window_border_hidpi on \
	window_border on \
	split_ratio 0.50 \
	split_type auto \
	auto_balance on \
	top_padding 0 \
	bottom_padding 0 \
	left_padding 0 \
	right_padding 0 \
	window_gap 4 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

# float apps
yabai -m rule --add title="^macpopup$" sticky=on manage=off
yabai -m rule --add app="^System Settings$" sticky=on manage=off
yabai -m rule --add app="^Calculator$" sticky=on manage=off
yabai -m rule --add app="^Books$" sticky=on manage=off
