#!/usr/bin/env sh

SCREEN_WIDTH=$(yabai -m query --displays --display | jq '.frame.w')
SCREEN_HEIGHT=$(yabai -m query --displays --display | jq '.frame.h')

TERM_COLUMNS=80
TERM_LINES=24

# approx height and width of 80 cols and 24 lines
TERM_WIDTH=750
TERM_HEIGHT=500

X=$(($SCREEN_WIDTH/2 - $TERM_WIDTH/2))
Y=$(($SCREEN_HEIGHT/2 - $TERM_HEIGHT/2))

alacritty -t "macpopup" \
    -o window.position.x="${X}" \
    -o window.position.y="${Y}" \
    -o window.dimensions.columns="${TERM_COLUMNS}" \
    -o window.dimensions.lines="${TERM_LINES}" \
    -e $1
