export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

export EDITOR="vim"

# Python user installed packages
export PATH="$HOME/.local/bin:$PATH"

# Golang
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
