# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Hides the default user@host when uneccesary.
DEFAULT_USER="daniel"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="eastwood-custom"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.zsh_custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=

# Do not store .zcompdump files in $HOME
export ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST

source $ZSH/oh-my-zsh.sh

# User configuration

# do not share history
setopt no_share_history

if [ -f "/opt/homebrew/bin/brew" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if [ -f "/usr/lib/google-cloud-sdk/completion.bash.inc" ]; then
  gcloud() {
    unset -f gcloud

    # This enables shell command completion for gcloud.
    # load bash completion functionality
    autoload bashcompinit
    bashcompinit
    source "/usr/lib/google-cloud-sdk/completion.bash.inc"

    gcloud $@
  }
fi

if [ -f "/usr/bin/terraform" ]; then
  terraform() {
    unset -f terraform

    # This enables shell command completion for terraform.
    # load bash completion functionality
    autoload -U +X bashcompinit && bashcompinit
    complete -o nospace -C /usr/bin/terraform terraform

    terraform $@
  }
fi

# Node Version Manager
export NVM_DIR="$HOME/.nvm"

if [ -s "$NVM_DIR/nvm.sh" ]; then
  NVIM_DEFAULT_ALIAS=$(< "$NVM_DIR/alias/default")

  # recursively follow the alias until it no longer resolves to a file
  while [ -f "$NVM_DIR/alias/$NVIM_DEFAULT_ALIAS" ]; do
    NVIM_DEFAULT_ALIAS=$(< "$NVM_DIR/alias/$NVIM_DEFAULT_ALIAS")
  done

  NVIM_DEFAULT_PATH="$NVM_DIR/versions/node/$NVIM_DEFAULT_ALIAS/bin"
  if ! [ -d $NVIM_DEFAULT_PATH ]; then
    # fallback to loading nvim the old way
    echo "slow loading nvm"
    \. "$NVM_DIR/nvm.sh"
  elif; then
    export PATH="$PATH:$NVIM_DEFAULT_PATH"

    # lazy load nvm
    nvm() {
      unset -f nvm
      export PATH=$(echo $PATH | sed -e "s#:$NVIM_DEFAULT_PATH##")
      \. "$NVM_DIR/nvm.sh"
      nvm $@
    }
  fi
fi

if [ -d "$HOME/.pyenv" ]; then
  export PATH="$HOME/.pyenv/bin:$PATH"
  eval "$(pyenv init -)"
fi

if [ -f "/usr/bin/direnv" ]; then
  eval "$(direnv hook zsh)"
fi

# fix ssh-agent forwarding for tmux
if [[ -n "$SSH_CONNECTION" && -n "$TMUX" ]]; then
  export SSH_AUTH_SOCK="$HOME/.ssh/ssh_auth_sock"
fi

# nvim
alias v="nvim"

# tmux
alias ta='tmux attach -t'
alias tn='tmux new -s $(basename $(pwd))'
alias t="$HOME/.config/tmux/plugins/t-smart-tmux-session-manager/bin/t"
alias tl='tmux list-sessions'
